export const PHYSICS = {
  MAX_SPEED: 28.0,
  ACCELERATION: 18.0,
  BRAKE_DECELERATION: 24.0,
  IDLE_DECELERATION: 8.0,
  TURN_SPEED: 2.8,
  TURN_REDUCTION_AT_SPEED: 0.6,
  DRIFT_TRIGGER_SPEED: 12.0,
  DRIFT_TURN_MULTIPLIER: 1.4,
  DRIFT_SPEED_PENALTY: 0.85,
  DRIFT_CHARGE_RATE: 40.0,
  DRIFT_BOOST_THRESHOLDS: [33, 66, 100],
  DRIFT_BOOST_SPEEDS: [1.2, 1.35, 1.5],
  DRIFT_BOOST_DURATIONS: [1.0, 1.5, 2.2],
  GRAVITY: 20.0,
  GROUND_RAYCAST_DISTANCE: 2.0,
  KART_HOVER_HEIGHT: 0.4,
  RESPAWN_HOVER_HEIGHT: 1.0,
  OFF_TRACK_SPEED_MULTIPLIER: 0.45,
  WALL_BOUNCE_RESTITUTION: 0.3,
  WALL_SPEED_PENALTY: 0.6,
  MINI_SPEED_MULTIPLIER: 0.65,
  BOOST_STAR_SPEED_MULTIPLIER: 1.4,
  MUSHROOM_BOOST_MULTIPLIER: 1.6,
  MUSHROOM_BOOST_DURATION: 2.5,
  LIGHTNING_SHRINK_DURATION: 5.0,
  STUN_DURATION: 1.2,
  LONG_STUN_DURATION: 2.5,
};

export const SURFACE_FRICTION = {
  default:       1.0,
  wood:          1.0,
  keyboard:      0.85,
  mousepad:      1.15,
  cardboard:     0.8,
  carpet:        0.7,
  clothing:      0.5,
  tile:          1.0,
  soap:          0.3,
  wet:           0.7,
  deck_wood:     0.9,
  rope:          0.6,
  anchor_chain:  1.1,
  coral:         0.9,
  sand:          0.75,
  ancient_stone: 1.1,
  marble:        1.1,
  rubble:        0.6,
  ice:           0.15,
  scorch:        0.95,
  cloud:         0.9,
  gold_stone:    1.1,
  vine:          0.6,
  asphalt:       1.0,
  wet_road:      0.7,
  concrete:      1.0,
  metal_grating: 0.85,
  gravel:        0.7,
  rooftop:       0.9,
  dirt:          0.65,
  scaffolding:   1.05,
  crane_metal:   1.1,
  branch:        0.9,
  mud:           0.5,
  temple_stone:  1.1,
  snow:          0.8,
  icy_rock:      0.2,
  crystal:       0.4,
  smooth_stone:  1.05,
  pcb:           0.9,
  copper:        1.1,
  solder:        0.8,
  pixel:         0.9,
  grass_block:   1.05,
  dirt_block:    0.7,
  arcade_carpet: 0.9,
  cabinet_top:   0.95,
  pinball_metal: 1.05,
  air_hockey:    0.5,
  grid_white:    0.9,
  obsidian:      1.1,
  ash_rock:      0.65,
  wet_stone:     0.8,
  sea_cave:      1.05,
  cliff_mud:     0.6,
  packed_sand:   0.85,
  sandstone:     1.05,
  canyon_rock:   1.0,
  glacier_ice:   0.2,
  ice_tunnel:    0.1,
  compacted_snow:0.8,
  moon_dust:     0.75,
  station_floor: 1.1,
  asteroid_rock: 0.65,
  crystal_patch: 1.1,
  debris:        0.7,
  alien_dirt:    0.85,
  alien_crystal: 1.1,
  city_floor:    1.1,
  frozen_river:  0.05,
};

export const KART_AABB = { x: 1.2, y: 0.8, z: 1.8 };
